### ISSUE TITLE
some iiif links don't work (all fragments?)

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/parzival-static-api#2]
All IIIF links in https://dhbern.github.io/parzival-static-api/api/json/metadata-ms-page/fr32.json provide the wrong link. The images are on the IIIF-Server though: https://iiif.ub.unibe.ch/admin/sequence/da57b27c-19cb-40a3-a599-45fc5a60852f .

Is the underscore in the filename putting it off?

**Comment by pdaengeli** [comment]
Some testing:

**Source file name 	D005.jpf**

* https://iiif.ub.unibe.ch/image/v3/Parzival/D005.jpf/info.json :green_circle: 

**Source file name 	032_001r.jpf**
* https://iiif.ub.unibe.ch/image/v3/Parzival/fr32001r.jpf/info.json (currently in the data) :red_circle: 
* https://iiif.ub.unibe.ch/image/v3/Parzival/fr32_001r.jpf/info.json (same with underscore) :red_circle: 
* https://iiif.ub.unibe.ch/image/v3/Parzival/032_001r.jpf/info.json (same as on IIIF server): :red_circle: 

**Underscores work well elsewhere**
* https://iiif.ub.unibe.ch/image/v3/haller/collection_00001_00001.tif/info.json :green_circle: 

Not sure yet what to make of this…

**Comment by pdaengeli** [comment]
Looks like many files were imported multiple times and not overwritten. Resolving of pretty IIIF paths (`Parzival/002_001r.jpf/info.json`) seems to fail in these cases.

Generally there should be guards against this in the ingest workflow, but for some reason the creation of duplicates was not prevented (perhaps  `jpf` extension slipped through some predefined pattern).

![image](https://github.com/DHBern/parzival-static-api/assets/6328618/ef10fc68-6c46-4db2-a854-6f31fc3cbe3a)

After deletion of duplicates resolving works as expected:

![image](https://github.com/DHBern/parzival-static-api/assets/6328618/151782fe-03be-4d3f-9495-37e249fcb5c2)

**Source file name 002_001r.jpf**

* https://iiif.ub.unibe.ch/image/v3/Parzival/002_001r.jpf/info.json :green_circle: 

## Course of action

- [ ] delete duplicates (this might be most efficiently done by UB IT)
- [ ] inform UB IT of the problem

**Comment by flicksolutions** [comment]
Thank you for finding out what went wrong!
I am excited to hear from UBIT. Could you let me know if you're contacting them, or should I?

**Comment by pdaengeli** [comment]
I got in touch, let's see.

**Comment by flicksolutions** [comment]
any update on this @pdaengeli ?

There's also something wrong in [sequence L](https://iiif.ub.unibe.ch/admin/sequence/e1cc360c-b304-4cd0-a47e-b306a6558488): pages 12 - 15 are there but have the wrong filename so for the app they don't exist. I didn't find out how to rename the files.

**Comment by flicksolutions** [comment]
yeah, without the `_alt` it should work. The app looks for `https://iiif.ub.unibe.ch/image/v3/Parzival/l012.jpf/info.json`

interestingly, the paths seem to be case-insensitive... (so we are quite lucky to have _m_ and _mk_ and not _M_ and _m_ as sigla...

**Comment by pdaengeli** [comment]
Renaming in the admin interface only affects the properties of the Presentation API, not the Image API. So we will need to re-import with new names (from whatever we have got on research storage). Can you have a look there?

> interestingly, the paths seem to be case-insensitive... (so we are quite lucky to have m and mk and not M and m as sigla...

Indeed, that wouldn't go well in various regards.

**Comment by flicksolutions** [comment]
> Did you encounter any other such cases?
I did not, but I also didn't go on an extensive bug hunt yet... I suspect a lot of bugs on all sides to be honest...

> Renaming in the admin interface only affects the properties of the Presentation API, not the Image API. So we will need to re-import with new names (from whatever we have got on research storage). Can you have a look there?

This is definitely a missing feature... to be able to rename stuff on every level. Should we report to UBIT?
It's curious: I can find the _alt images even on resstore (Projekt_Parzival\projekte-stolz\data\images\parzival\l)! And the pictures that are missing on the IIIF are written with lowercase l. All others with uppercase L...
I'll try to reupload them tomorrow...

**Comment by pdaengeli** [comment]
* https://iiif.ub.unibe.ch/image/v3/Parzival/l012.jpf/info.json :green_circle: 
* https://iiif.ub.unibe.ch/image/v3/Parzival/l013.jpf/info.json :green_circle: 
* https://iiif.ub.unibe.ch/image/v3/Parzival/l014.jpf/info.json :green_circle: 
* https://iiif.ub.unibe.ch/image/v3/Parzival/l015.jpf/info.json :green_circle: 

All working now.

> This is definitely a missing feature... to be able to rename stuff on every level. Should we report to UBIT?

I guess they are ready to do this on request, but might be skeptical to offer the functionality in the GUI (as is the case for inter-project moving).

Ask anyways or close here?

**Comment by flicksolutions** [comment]
Thanks for your help.
I guess if they get too many requests they will introduce the feature themselves... ;-)

Close here.
