### ISSUE TITLE
provide PDFs of Fassungsansicht (`dist/api/export/pdf|tex|tustep`)

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/parzival-static-api#3]
According to our discussion in discord and via Mail with Dominique:

create action/process that is manually triggered and does the following:

- [ ] GET https://parzival.unibe.ch/parzdb/parzival.php?page=pdf&dreissiger=1 to https://parzival.unibe.ch/parzdb/parzival.php?page=pdf&dreissiger=827
- [ ] provide PDFs in this repository for reuse in [presentation-parzival](https://github.com/DHBern/presentation_parzival)

**Comment by pdaengeli** [comment]
I meant to have opened this, but never submitted…

Here's the implementation plan:

* Create wrapper script
* Embed existing command
* Optionally fetch pdf/tex/tustep files from existing interface and make them available in appropriate directory (`dist/api/pdf`, `dist/api/tex`, `dist/api/tustep`)

**Comment by pdaengeli** [comment]
Something went wrong with `tex` exports, will check later.
