### ISSUE TITLE
provide Textexport Data (`dist/api/export/txt`)

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/parzival-static-api#4]
According to our discussion in Discord and via Mail with Dominique:

Create action/process that is manually triggered and does the following:

- [ ] POST https://parzival.unibe.ch/parzdb/parzival.php?page=txtexport with the payload: "vc=Fassung%3A+*m+%5B*m%5D&minDr=1&maxDr=" (other payloads to find via browser-inspector)
- [ ] provide .txt-Files in this repository for reuse in [presentation-parzival](https://github.com/DHBern/presentation_parzival)

**Comment by pdaengeli** [comment]
What's a good target directory here? `dist/api/??`

`txt` feels too general given the relatively specific form of the output:

```
;;;1;1;;Ist zwîvel herzen nâchgebûr,
;;;1;2;;daz muoz der sêle werden sûr.
;;;1;3;;gesmæhet unde gezieret
;;;1;4;;ist, swâ sich parrieret
;;;1;5;;unverzaget mannes muot,
;;;1;6;;als agelstern varwe tuot.
;;;1;7;;der mac dennoch wesen geil,
;;;1;8;;wand an im sint beidiu teil,
;;;1;9;;des himels und der helle.
;;;1;10;;der unstæte geselle
;;;1;11;;hât die swarzen varwe gar
;;;1;12;;und wirt ouch nâch der vinster var.
```

**Comment by flicksolutions** [comment]
how about `dist/api/export/txt`?

**Comment by pdaengeli** [comment]
Good one. Let's use the `export` segment also for #3, makes sense everywhere.
