### ISSUE TITLE
generate list of all verses

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/parzival-static-api#8]
If we are going to pregenerate all content, we will need a complete list of verse numbering. Right now, the app assumes there are 827 * 30 verses. But this is not entirely correct since there are additional verses now and then.

Can you get me a complete list of all possible verse numbering? I don't care about the sigla they would match (since I need an error page for every sigla they don't match anyway).

The ideal would be a JSON that is formed like this:

```json
 {
  d: [1.1, 1.2, 1.3, 1.3-10, 1.4, ...],
  I: [...]
 }
```

Thanks a lot!

**Comment by pdaengeli** [comment]
There are now lists per document

* https://dhbern.github.io/parzival-static-api/api/json/metadata-ms-verses/

as well as a global list

* https://dhbern.github.io/parzival-static-api/api/json/metadata-ms-verses.json

Which format do you prefer, @flicksolutions?

**Comment by flicksolutions** [comment]
Thank you so much! That looks very good.
I prefer the global list.
the *perfect* structure would be this:
```
{
  d (handle): {
               1 (dreissiger): [1,2,3,4,5,...,30] (vers)
                }
 }
```

But I can also work with the global list, no problem.
In the end I will have an Array with ~24500 Objects that look like this:
```
{
  sigla: 'd',
  thirties: '1',
  verse: '01'
}
```

(but to have that in the backend API might be a bit overkill and too big a file...

**Comment by pdaengeli** [comment]
This wouldn't be hard to produce: 

```
{
  "meta": {
    "generated-by": "parzival-static-api\/src\/generate.xsl",
    "task": "metadata-ms-verses",
    "generated-on": "2024-10-05T10:14:19.323696608Z",
    "description": "Verse numbers contained in source document."
  },
  "verses": [
    { "siglum":"d", "thirties":"1", "verse":"01-01" },
    { "siglum":"d", "thirties":"1", "verse":"01-02" },
    { "siglum":"d", "thirties":"1", "verse":"01" },
    { "siglum":"d", "thirties":"1", "verse":"02" },
    { "siglum":"d", "thirties":"1", "verse":"03" },
    { "siglum":"d", "thirties":"1", "verse":"04" },
    { "siglum":"d", "thirties":"1", "verse":"05" },
    { "siglum":"d", "thirties":"1", "verse":"06" },
    { "siglum":"d", "thirties":"1", "verse":"07" },
    { "siglum":"d", "thirties":"1", "verse":"08" },
    { "siglum":"d", "thirties":"1", "verse":"09" },
    { "siglum":"d", "thirties":"1", "verse":"10" },
    { "siglum":"d", "thirties":"1", "verse":"11" },
    { "siglum":"d", "thirties":"1", "verse":"12" },
    { "siglum":"d", "thirties":"1", "verse":"13" },
    { "siglum":"d", "thirties":"1", "verse":"14" },
    { "siglum":"d", "thirties":"1", "verse":"15" },
    { "siglum":"d", "thirties":"1", "verse":"16" },
-------------------------8<-------------------------------
    { "siglum":"z", "thirties":"827", "verse":"15" },
    { "siglum":"z", "thirties":"827", "verse":"16" },
    { "siglum":"z", "thirties":"827", "verse":"17" },
    { "siglum":"z", "thirties":"827", "verse":"18" },
    { "siglum":"z", "thirties":"827", "verse":"19" },
    { "siglum":"z", "thirties":"827", "verse":"20" },
    { "siglum":"z", "thirties":"827", "verse":"21" },
    { "siglum":"z", "thirties":"827", "verse":"22" },
    { "siglum":"z", "thirties":"827", "verse":"23" },
    { "siglum":"z", "thirties":"827", "verse":"24" },
    { "siglum":"z", "thirties":"827", "verse":"25" },
    { "siglum":"z", "thirties":"827", "verse":"26" },
    { "siglum":"z", "thirties":"827", "verse":"27" },
    { "siglum":"z", "thirties":"827", "verse":"28" },
    { "siglum":"z", "thirties":"827", "verse":"29" },
    { "siglum":"z", "thirties":"827", "verse":"30" }
  ]
}
```
[metadata-ms-verses.json](https://github.com/user-attachments/files/17265786/metadata-ms-verses.json)

A tad heavy (18.6mb / 410'000 maps), but not dramatic,

What do you think?

**Comment by flicksolutions** [comment]
absolutely brilliant! I can take that as is for most routes! Thank you!!

**Comment by pdaengeli** [comment]
Now available in https://dhbern.github.io/parzival-static-api/api/json/metadata-ms-verses.json
